parent=keycloak.v2
import=common/keycloak

styles=css/login.css

kcLoginClass=pf-v5-c-login__main synapse-login-card

kcFormGroupClass=pf-v5-c-form__group
kcLabelClass=pf-v5-c-form__label
kcInputClass=pf-v5-c-form-control
kcInputGroup=pf-v5-c-input-group
kcInputErrorMessageClass=pf-v5-c-helper-text__item-text pf-m-error kc-feedback-text
kcAlertClass=pf-v5-c-alert pf-m-inline pf-v5-u-mb-md
kcAlertTitleClass=pf-v5-c-alert__title
kcFormPasswordVisibilityButtonClass=pf-v5-c-button pf-m-control
kcFormPasswordVisibilityIconShow=fa-eye fas
kcFormPasswordVisibilityIconHide=fa-eye-slash fas

kcButtonClass=pf-v5-c-button
kcButtonPrimaryClass=pf-m-primary
kcButtonDefaultClass=pf-m-secondary
kcButtonBlockClass=pf-m-block
kcFormClass=pf-v5-c-form pf-v5-u-w-100
kcFormButtonsClass=synapse-form-buttons

kcCheckboxClass=pf-v5-c-check
kcCheckboxInputClass=pf-v5-c-check__input
kcCheckboxLabelClass=pf-v5-c-check__label
